<?php
/**
 * MyBB 1.8 Merge System
 * Copyright 2022 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/download/merge-system/license/
 */

define('MERGE_DATATYPE_UNKNOWN', 'unknown');
define('MERGE_DATATYPE_BOOL', 'bool');
define('MERGE_DATATYPE_BIT', 'bit');
define('MERGE_DATATYPE_INT', 'int');
define('MERGE_DATATYPE_FIXED', 'fixed');
define('MERGE_DATATYPE_FLT', 'flt');
define('MERGE_DATATYPE_DBL', 'dbl');
define('MERGE_DATATYPE_CHAR', 'char');
define('MERGE_DATATYPE_BIN', 'bin');

define('MERGE_DATATYPE_INT_TINYINT_MIN', '-128');
define('MERGE_DATATYPE_INT_TINYINT_MAX', '127');
define('MERGE_DATATYPE_INT_TINYINT_MIN_UNSIGNED', '0');
define('MERGE_DATATYPE_INT_TINYINT_MAX_UNSIGNED', '255');
define('MERGE_DATATYPE_INT_SMALLINT_MIN', '-32768');
define('MERGE_DATATYPE_INT_SMALLINT_MAX', '32767');
define('MERGE_DATATYPE_INT_SMALLINT_MIN_UNSIGNED', '0');
define('MERGE_DATATYPE_INT_SMALLINT_MAX_UNSIGNED', '65535');
define('MERGE_DATATYPE_INT_MEDIUMINT_MIN', '-8388608');
define('MERGE_DATATYPE_INT_MEDIUMINT_MAX', '8388607');
define('MERGE_DATATYPE_INT_MEDIUMINT_MIN_UNSIGNED', '0');
define('MERGE_DATATYPE_INT_MEDIUMINT_MAX_UNSIGNED', '16777215');
define('MERGE_DATATYPE_INT_INTEGER_MIN', '-2147483648');
define('MERGE_DATATYPE_INT_INTEGER_MAX', '2147483647');
define('MERGE_DATATYPE_INT_INTEGER_MIN_UNSIGNED', '0');
define('MERGE_DATATYPE_INT_INTEGER_MAX_UNSIGNED', '4294967295');
define('MERGE_DATATYPE_INT_BIGINT_MIN', '-9223372036854775808');
define('MERGE_DATATYPE_INT_BIGINT_MAX', '9223372036854775807');
define('MERGE_DATATYPE_INT_BIGINT_MIN_UNSIGNED', '0');
define('MERGE_DATATYPE_INT_BIGINT_MAX_UNSIGNED', '18446744073709551615');

define('MERGE_DATATYPE_CHAR_LENGTHTYPE_CHAR', 'char');
define('MERGE_DATATYPE_CHAR_LENGTHTYPE_BYTE', 'byte');

define('MERGE_DATATYPE_CHAR_TINYTEXT_LENGTH', 255);
define('MERGE_DATATYPE_CHAR_TEXT_LENGTH', 65535);
define('MERGE_DATATYPE_CHAR_TEXT_LENGTH_PGSQL', 1073741824);
define('MERGE_DATATYPE_CHAR_TEXT_LENGTH_SQLITE', 2147483647);
define('MERGE_DATATYPE_CHAR_MEDIUMTEXT_LENGTH', 16777215);
define('MERGE_DATATYPE_CHAR_LONGTEXT_LENGTH', 4294967295);

define('MERGE_DATATYPE_BIN_TINYBLOB_LENGTH', 255);
define('MERGE_DATATYPE_BIN_BLOB_LENGTH', 65535);
define('MERGE_DATATYPE_BIN_BLOB_LENGTH_PGSQL', 1073741824);
define('MERGE_DATATYPE_BIN_BLOB_LENGTH_SQLITE', 2147483647);
define('MERGE_DATATYPE_BIN_MEDIUMBLOB_LENGTH', 16777215);
define('MERGE_DATATYPE_BIN_LONGBLOB_LENGTH', 4294967295);
